parser: 'babel-eslint'
env:
  node: true
  browser: true
  commonjs: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
plugins:
  - react
settings:
  react:
    version: 'latest'
rules:
  indent:
    - warn
    - tab
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
