parser: 'babel-eslint'
env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
plugins:
  - react
rules:
  indent:
    - warn
    - tab
  linebreak-style:
    - warn
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
