language: node_js
node_js:
    - "8"
dist: trustys
services:
  - postgres
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - frontend/node_modules
    - server/node_modules
install:
  - npm install
script:
  - npm run test
deploy:
  provider: heroku
  api_key: $HEROKU_SECRET_KEY
  app:
    master: web-api-exam
