env:
  browser: true
  es6: true
extends:
  - 'airbnb-base'
rules:
  brace-style:
    - warn
    - stroustrup
  comma-dangle:
    - warn
    - never
  no-unused-vars:
    - warn
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
